apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-aplicacion
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mi-aplicacion
  template:
    metadata:
      labels:
        app: mi-aplicacion
    spec:
      containers:
      - name: mi-aplicacion
        image: 641904109053.dkr.ecr.us-east-1.amazonaws.com/repoweb:latest  # URL de tu imagen en ECR
        ports:
        - containerPort: 80  # El puerto dentro del contenedor

