apiVersion: v1
kind: Service
metadata:
  name: mi-aplicacion-service
spec:
  selector:
    app: mi-aplicacion  # Debe coincidir con la etiqueta del Deployment
  ports:
    - protocol: TCP
      port: 80  # Puerto expuesto por el ELB
      targetPort: 80  # Puerto dentro de los pods
  type: LoadBalancer  # Tipo de servicio para exponer la aplicación externamente

